# Generated by Django 3.0.3 on 2020-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0002_auto_20200507_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
