# Generated by Django 3.0.3 on 2020-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0003_auto_20200511_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
