# Generated by Django 3.0.3 on 2020-05-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0007_auto_20200511_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
