# Generated by Django 3.0.3 on 2020-05-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0010_auto_20200511_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='received_requests',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sent_requests',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='friendship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='userr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redes_backend.Friend'),
        ),
    ]
