# Generated by Django 3.0.3 on 2020-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0015_friend_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_photo',
            field=models.ImageField(default='default_banner.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to=''),
        ),
    ]
