# Generated by Django 3.0.3 on 2020-05-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0016_auto_20200515_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
