# Generated by Django 3.0.3 on 2020-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='redes_backend.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='received_requests',
            field=models.ManyToManyField(blank=True, related_name='received', to='redes_backend.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='sent', to='redes_backend.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
