# Generated by Django 3.0.3 on 2020-04-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redes_backend.User')),
                ('friends', models.ManyToManyField(blank=True, related_name='_friend_friends_+', to='redes_backend.User')),
                ('received_requests', models.ManyToManyField(blank=True, related_name='_friend_received_requests_+', to='redes_backend.User')),
                ('sent_requests', models.ManyToManyField(blank=True, related_name='_friend_sent_requests_+', to='redes_backend.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Friended',
        ),
    ]
