# Generated by Django 3.0.3 on 2020-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0004_auto_20200511_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_photo',
            field=models.ImageField(blank=True, default='default_banner.png', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='photos/'),
        ),
    ]
