# Generated by Django 3.0.3 on 2020-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0011_auto_20200512_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, to='redes_backend.Friend'),
        ),
    ]
