# Generated by Django 3.0.3 on 2020-05-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0012_auto_20200512_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='redes_backend.Friend'),
        ),
    ]
