# Generated by Django 3.0.3 on 2020-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_backend', '0014_auto_20200512_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='user_photo',
            field=models.ImageField(default='default_profile.png', upload_to='media'),
        ),
    ]
